name: .NET

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Boostrap
      run: mkdir -p /home/ec2-user/.dotnet

    - name: Build
      run: make cibuild

    - name: Test
      run: make citest

  acceptance-test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Boostrap
      run: mkdir -p /home/ec2-user/.dotnet

    - name: Build
      run: make cibuild

    - name: Run acceptance tests
      run: make citest-acceptance

    - name: Copy results
      if: always()
      run: cp -r LevelUpGame.Tests/resources ./test-results

    - name: Export pretty results
      if: always()
      run: export DOTNET_CLI_HOME=/home/ec2-user/.dotnet & export DOTNET_ROOT=$(which dotnet) & /home/ec2-user/.dotnet/tools/livingdoc test-assembly LevelUpGame.Tests/bin/Debug/net6.0/LevelUpGame.Tests.dll -t LevelUpGame.Tests/bin/Debug/net6.0/TestExecution.json -o test-results/TestOutput.html

    - name: Publish Tests
      if: always()
      uses: level-up-program-dev/actions-gh-pages@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-results